package com.java.inventory.system.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.Builder;
import lombok.Data;

/**
 * Represents a product in the inventory system.
 * This class is mapped to a database table using JPA annotations.
 */
@Entity
@Data
@Builder
public class Product {

    /**
     * The unique identifier for the product.
     * This field is auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    /**
     * The name of the product.
     */
    private String name;
    /**
     * A brief description of the product.
     */
    private String description;
    /**
     * The type/category of the product (e.g., food, sports, household, music, electronic,
     * appliance, etc.).
     */
    private String productType;
    /**
     * The available quantity of the product in the inventory.
     */
    private int quantity;
    /**
     * The price per unit of the product.
     */
    private double unitPrice;

    /**
     * Default constructor for the {@link Product} class.
     */
    public Product() {
    }

    /**
     * Constructor for creating a {@link Product} with specified values.
     *
     * @param id          the unique identifier for the product.
     * @param name        the name of the product.
     * @param description a description of the product.
     * @param productType the type/category of the product.
     * @param quantity    the available quantity of the product.
     * @param unitPrice   the price per unit of the product.
     */
    public Product(Long id, String name, String description, String productType, int quantity, double unitPrice) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.productType = productType;
        this.quantity = quantity;
        this.unitPrice = unitPrice;
    }
}
